### ISSUE TITLE
How can I use TransE to pretrain the embedding instead of directly downloading

### ISSUE THREAD

**Issue by dayuyang1999** [dengyang17/unicorn#4]
Hi,

In the Readme file, You said "Use TransE from [[OpenKE](https://github.com/thunlp/OpenKE)] to pretrain the graph embeddings. And put the pretrained embeddings under "unicorn/tmp/<data_name>/embeds/"."

I am wondering how can I get these embeddings if I am unable to download them from Google Drive?

Is there any function that is contained in the code allowing me to do that?

Thanks.

**Comment by ghost** [comment]
你好，不能下载的话。只能自己去openke训练得到。他的代码里面不包含这部分代码。



---- 回复的原邮件 ----
| 发件人 | Dayu ***@***.***> |
| 日期 | 2022年04月17日 09:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [dengyang17/unicorn] How can I use TransE to pretrain the embedding instead of directly downloading (Issue #4) |

Hi,

In the Readme file, You said "Use TransE from [OpenKE] to pretrain the graph embeddings. And put the pretrained embeddings under "unicorn/tmp/<data_name>/embeds/"."

I am wondering how can I get these embeddings if I am unable to download them from Google Drive?

Is there any function that is contained in the code allowing me to do that?

**Comment by dayuyang1999** [comment]
> 

谢谢你的快速解答！
